package com.ftn.sbnz.model.enums;

public enum AnalyticStatusType {

    PROTEIN_WARNING,
    PROTEIN_DISTRIBUTION_CONFLICT,
    PROTEIN_CRITICAL,
    LOW_PROTEIN_MEAL,

    ENERGY_SHORTAGE,
    OVEREATING_DETECTED,

    MUSCLE_LOSS_RISK,

    WEIGHT_STAGNATION_CONFIRMED,
    CALORIC_ADAPTATION_BLOCK,
    PLAN_CHANGE_NEEDED,

    EXTREME_CALORIC_RESTRICTION,
    CALORIC_SURPLUS_ACCUMULATION
}