package rules;

import com.ftn.sbnz.model.enums.DailyIntakeStatus;
import com.ftn.sbnz.model.enums.MealCategory;
import com.ftn.sbnz.model.events.MealSkipped;
import com.ftn.sbnz.model.models.BingePattern;
import com.ftn.sbnz.model.models.BreakfastSkippingPattern;
import com.ftn.sbnz.model.models.DailyIntake;
import com.ftn.sbnz.model.models.LateNightEatingPattern;
import com.ftn.sbnz.model.models.Meal;
import com.ftn.sbnz.model.models.User;

rule "Generated Template Maintenance Stability"
when
    $user : User($userId : id, $target : targetCalories > 0)
    $intake : DailyIntake(
        userId == $userId,
        totalCalories >= ($target * 0.95),
        totalCalories <= ($target * 1.05),
        status != DailyIntakeStatus.MAINTENANCE_STABLE
    )
then
    modify($intake) {
        setStatus(DailyIntakeStatus.MAINTENANCE_STABLE)
    }
end

rule "Generated Template Breakfast Skipping Pattern"
when
    $user : User($userId : id)
    Number(intValue >= 3) from accumulate(
        MealSkipped(userId == $userId, category == MealCategory.BREAKFAST),
        count(1)
    )
    not BreakfastSkippingPattern(userId == $userId)
then
    insert(new BreakfastSkippingPattern($userId, java.time.LocalDate.now(), 3));
end

rule "Generated Template Late Night Eating Pattern"
when
    $user : User($userId : id)
    Number(intValue >= 3) from accumulate(
        Meal(userId == $userId, (timestamp.getHour() >= 22 || timestamp.getHour() < 6)),
        count(1)
    )
    not LateNightEatingPattern(userId == $userId, lateMealCount >= 3)
then
    insert(new LateNightEatingPattern($userId, java.time.LocalDate.now(), 3));
end

rule "Generated Template Binge Pattern"
when
    $user : User($userId : id)
    Number(intValue >= 3) from accumulate(
        Meal(userId == $userId) over window:time(90m),
        count(1)
    )
    not BingePattern(userId == $userId)
then
    insert(new BingePattern($userId, java.time.LocalDate.now(), 3, 90));
end
